name: Check Branch and Python Version

on:
  push:
    branches:
      - task-1
      - task-2
      - task-3
      - task-4
      - task-5

jobs:
  check-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show current branch
        run: echo "Current branch is ${{ github.ref_name }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Show Python version
        run: python --version